version: "3"
services:

  api-1:
    build:
      dockerfile: api/Dockerfile
      context: .
    environment:
      - REDIS_CONNECTION_STRING=redis://kiso-redis-stack:6379
      - MONGO_CONNECTION_STRING=mongodb://kiso-mongo:27017
    depends_on:
      - mongo
      - redis-stack
    container_name: kiso-api-1

  worker-1:
    build:
      dockerfile: worker/Dockerfile
      context: .
    environment:
      - REDIS_CONNECTION_STRING=redis://kiso-redis-stack:6379
      - BUILD_LANGUAGE_IMAGES=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - redis-stack
      - dotnet-sandbox
      - python-sandbox
    container_name: kiso-worker-1

  reducer-1:
    build:
      dockerfile: reducer/Dockerfile
      context: .
    environment:
      - REDIS_CONNECTION_STRING=redis://kiso-redis-stack:6379
      - MONGO_CONNECTION_STRING=mongodb://kiso-mongo:27017
    depends_on:
      - mongo
      - redis-stack
    container_name: kiso-reducer-1

  redis-stack:
    image: redis/redis-stack
    ports:
      - "8001:8001"
      - "6379:6379"
    expose:
      - "8001"
      - "6379"
    container_name: kiso-redis-stack

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    container_name: kiso-mongo

  dotnet-sandbox:
    build:
      dockerfile: dotnet6.Dockerfile
      context: worker/src/main/resources/docker
      args:
        DOCKER_SANDBOX_USER: sandbox-user
        DOCKER_SANDBOX_WORKDIR: sandbox-tmpfs
        DOCKER_SANDBOX_INPUTDIR: sandbox-input
    image: dotnet-sandbox
    container_name: dotnet-sandbox-test

  python-sandbox:
    build:
      dockerfile: python3.Dockerfile
      context: worker/src/main/resources/docker
      args:
        DOCKER_SANDBOX_USER: sandbox-user
        DOCKER_SANDBOX_WORKDIR: sandbox-tmpfs
        DOCKER_SANDBOX_INPUTDIR: sandbox-input
    image: python-sandbox
    container_name: python-sandbox-test